task:
  collect1:
    level: 1
    type: collect
    info:
      name: 新手收集-10个橡木
      lore:
        - 这是一个收集任务
        - 新手任务都是很简单的任务
      item: 17-0-10
    submit:
      - 17-0-10
    reward:
      - 264-0-1
  craft1:
    level: 2
    type: craft
    info:
      name: 新手合成-1个工作台
      lore:
        - 这是一个合成任务
        - 合成任务自动检测完成
      item: 58-0-1
    craft:
      - 58-0-1
    reward:
      - 265-0-16

player:
  knkiss:
    level: 1

settings:
  maxlevel: 100
  saveTiming: 60