task:
  collect1:
    level: 1
    type: collect
    info:
      name: 新手收集-10个橡木
      lore:
        - 这是一个收集任务
        - 收集任务需要手动提交
      item: 17-0-10
    submit:
      - 17-0-10
    reward:
      - 264-0-1
  craft1:
    level: 2
    type: craft
    info:
      name: 新手合成-1个工作台
      lore:
        - 这是一个合成任务
        - 合成任务自动检测完成
      item: 58-0-1
    craft:
      - 58-0-1
    reward:
      - 265-0-16
  kill1:
    level: 3
    type: kill
    info:
      name: 新手击杀-1个僵尸
      lore:
        - 这是一个击杀任务
        - 击杀任务自动检测完成
      item: 3-0-1
    kill:
    - 54-2
    - 52-1
    - 51-5
    reward:
      - 266-0-10
player:
  knkiss:
    level: 1

settings:
  maxlevel: 100
  saveTiming: 60