task:
  collect1:
    level: 1
    type: collect
    info:
      name: 新手收集-10个橡木
      lore:
        - 这是一个收集任务
        - 可通过指令或者任务列表提交
        - 从下文开始所有的x-x-x表示[物品ID-耐久-数量]
      item: 17-0-10
    submit:
      - 17-0-10
    reward:
      - 264-0-1
  craft1:
    level: 2
    type: craft
    info:
      name: 新手合成-1个工作台
      lore:
        - 这是一个合成任务
        - 自动检测完成
      item: 58-0-1
    craft:
      - 58-0-1
    reward:
      - 265-0-16
  kill1:
    level: 3
    type: kill
    info:
      name: 新手击杀-1个僵尸
      lore:
        - 这是一个击杀任务
        - 自动检测完成
        - 下文的X-X表示[怪物ID-数量]
        - 怪物ID可通过压缩包内help.md文件查看
        - 后续会增加可视化编辑
      item: 3-0-1
    kill:
    - 54-2
    reward:
      - 266-0-10
  location1:
    level: 4
    type: location
    info:
      name: 新手抵达-2个地点
      lore:
        - 这是一个抵达任务
        - 抵达任务需在标记点使用打火石点火
        - 下文X-X-X-X表示[X-Y-Z-世界]
        - 世界的名字随便写代表主世界
      item: 4-0-1
    location:
      - 550-68-381-World
      - 532-69-380-World
    reward:
      - 265-0-10

settings:
  maxlevel: 100 #尽量与任务数量匹配
  saveTiming: 60 #保存一次玩家数据间隔时间，内存占用很小